services:
  - type: web
    name: form-calisthenics-app
    runtime: docker
    plan: free
    region: ohio
    branch: master
    healthCheckPath: /up
    autoDeployTrigger: "off"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_MAX_THREADS
        value: "5"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"
